/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard/vehicles'
import { Route as DashboardCollectionsRouteImport } from './routes/dashboard/collections'
import { Route as DashboardCitizensRouteImport } from './routes/dashboard/citizens'
import { Route as DashboardBinsRouteImport } from './routes/dashboard/bins'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollectionsRoute = DashboardCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitizensRoute = DashboardCitizensRouteImport.update({
  id: '/citizens',
  path: '/citizens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBinsRoute = DashboardBinsRouteImport.update({
  id: '/bins',
  path: '/bins',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bins': typeof DashboardBinsRoute
  '/dashboard/citizens': typeof DashboardCitizensRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bins': typeof DashboardBinsRoute
  '/dashboard/citizens': typeof DashboardCitizensRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bins': typeof DashboardBinsRoute
  '/dashboard/citizens': typeof DashboardCitizensRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/bins'
    | '/dashboard/citizens'
    | '/dashboard/collections'
    | '/dashboard/vehicles'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/bins'
    | '/dashboard/citizens'
    | '/dashboard/collections'
    | '/dashboard/vehicles'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/bins'
    | '/dashboard/citizens'
    | '/dashboard/collections'
    | '/dashboard/vehicles'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collections': {
      id: '/dashboard/collections'
      path: '/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof DashboardCollectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/citizens': {
      id: '/dashboard/citizens'
      path: '/citizens'
      fullPath: '/dashboard/citizens'
      preLoaderRoute: typeof DashboardCitizensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bins': {
      id: '/dashboard/bins'
      path: '/bins'
      fullPath: '/dashboard/bins'
      preLoaderRoute: typeof DashboardBinsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBinsRoute: typeof DashboardBinsRoute
  DashboardCitizensRoute: typeof DashboardCitizensRoute
  DashboardCollectionsRoute: typeof DashboardCollectionsRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBinsRoute: DashboardBinsRoute,
  DashboardCitizensRoute: DashboardCitizensRoute,
  DashboardCollectionsRoute: DashboardCollectionsRoute,
  DashboardVehiclesRoute: DashboardVehiclesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
